
FROM nginx:1.21-alpine

# Copy our default nginx config
COPY nginx.conf /etc/nginx/

# Remove default configuration file
RUN rm -f /etc/nginx/conf.d/default.conf

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy over the artifacts in dist/ folder to default nginx public folder
COPY dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

