---
name: release

on:
  push:
    tags:
      - "*@*"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CARGO_HOME: "${{ github.workspace }}/.cargo/"
  GOPATH: "${{ github.workspace }}/.go/"
  GIT_DEPTH: 0

jobs:
  affected:
    runs-on: ubuntu-20.04
    container: ghcr.io/smlcorp/app-center:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          action-name: release-build

      - name: Set version and app
        shell: bash
        run: |
          echo "APP=$(echo ${{ github.ref_name }} | cut -d'@' -f1)" >> "$GITHUB_ENV"
          echo "VERSION=$(echo ${{ github.ref_name }} | cut -d'@' -f2)" >> "$GITHUB_ENV"

      - name: build
        shell: bash
        run: pnpm nx run ${{env.APP}}:build --production --optimization --configuration=ci --skip-nx-cache

      - name: package
        shell: bash
        run: pnpm nx run ${{env.APP}}:package --build=false --push --tag=${{ env.VERSION }} --skip-nx-cache
